name: Build & Run tests

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Run KtLint Check
        run: ./gradlew ktlintCheck

      - name: Run unit tests
        run: ./gradlew clean testDebug

      - name: Build Project
        run: ./gradlew :app:buildDebug

      - name: Generate Debug APK
        run: ./gradlew :app:assembleDebug --stacktrace

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk


